version: "2"

run:
  allow-parallel-runners: true
  go: "1.24"

issues:
  max-same-issues: 0
  new-from-rev: HEAD

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - gocyclo
    - cyclop
    - errcheck
    - unused
    - ineffassign
    - asciicheck
    - bodyclose
    - containedctx
    - contextcheck
    - makezero
    - nilerr

  settings:
    exhaustive:
      default-signifies-exhaustive: true

    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true

    errorlint:
      errorf: false

    gocyclo:
      min-complexity: 15

    cyclop:
      max-complexity: 15
      package-average: 0.5

  exclusions:
    rules:
      - linters:
          - cyclop
        path: cmd
    paths:
      - 'generator/*\\.go$'

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
