// SPDX-License-Identifier: MIT
// Copyright (c) 2022-2026 Dmitry Kisler <https://www.dkisler.com>, <admin@dkisler.com>
//
// WARNING: DO NOT EDIT!
// This file was auto-generated by github.com/kislerdm/neon-sdk-go/generator using the OpenAPI specifications
// from https://d216pytvakpmhr.cloudfront.net/api_spec/main/v2.json 
module github.com/kislerdm/neon-sdk-go

go 1.24

// faulty API response treatment for the methods:
// DeleteProjectBranch, DeleteProjectBranchDatabase, DeleteProjectBranchRole, DeleteProjectEndpoint
retract [v0.17.0, v0.19.0]
